#!/bin/sh
# location: /etc/pm/sleep.d/
# http://askubuntu.com/questions/873626/crash-when-toggling-off-caps-lock

case $1 in
     resume|thaw)
	 xinput set-prop "AT Raw Set 2 keyboard" "Device Enabled" 0
        ;;
esac
